version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: root1
    restart: always
    # ports:
    # - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
